// Generated by Wrangler by running `wrangler types`

interface Env {
	ADMIN_EMAILS: "mike.r.berardi@gmail.com";
	OVERSEER_CRAWL_URL: "https://overseer-crawl.libertydesignstudio.workers.dev";
	AUTH_SECRET: string;
	STRIPE_PRICE_ID: string;
	APP_URL: string;
	TV_URL: string;
	DEMO_LOGIN_PASSWORD: string;
	STRIPE_API_KEY: string;
	BROWSERLESS_TOKEN: string;
	SESSION: DurableObjectNamespace<import("./src/index").SessionDurableObject>;
	ACCOUNTS: DurableObjectNamespace<import("./src/index").AccountDurableObject>;
	STATS: DurableObjectNamespace<import("./src/index").StatsDurableObject>;
	DOMAINS: DurableObjectNamespace<import("./src/index").DomainDurableObject>;
	UPLOADS: R2Bucket;
}
