import type { MenuConfig, Category } from './types';

export const STARTER_DISPENSARY_NAME = 'Green Leaf Dispensary';

export const starterCategories: Category[] = [
  {
    id: 'cat-flower',
    name: 'Flower',
    order: 0,
    products: [
      {
        id: 'prod-og-kush',
        name: 'OG Kush',
        price: 45,
        thc: '24%',
        cbd: '<1%',
        weight: '3.5g',
        brand: 'Connected Cannabis Co.',
        strain: 'indica',
        inStock: true,
        description: 'Classic indica-dominant strain with earthy pine and lemon notes.',
        priceTiers: [
          { label: '1g', price: '$15' },
          { label: '3.5g', price: '$45' },
          { label: '7g', price: '$85' },
        ],
      },
      {
        id: 'prod-blue-dream',
        name: 'Blue Dream',
        price: 40,
        thc: '21%',
        cbd: '<1%',
        weight: '3.5g',
        brand: 'Wonderbrett',
        strain: 'sativa',
        inStock: true,
        description: 'Sweet berry aroma with balanced full-body relaxation.',
        priceTiers: [
          { label: '1g', price: '$14' },
          { label: '3.5g', price: '$40' },
          { label: '7g', price: '$78' },
        ],
      },
      {
        id: 'prod-gelato',
        name: 'Gelato #33',
        price: 48,
        thc: '25%',
        cbd: '<1%',
        weight: '3.5g',
        brand: 'Sherbinskis',
        strain: 'hybrid',
        inStock: true,
        description: 'Dessert-like hybrid with creamy citrus flavor and euphoric effects.',
      },
      {
        id: 'prod-runaway',
        name: 'Runtz',
        price: 50,
        thc: '27%',
        cbd: '<1%',
        weight: '3.5g',
        brand: 'Cookies',
        strain: 'hybrid',
        inStock: true,
        description: 'Award-winning strain known for its sugary, fruity profile.',
      },
    ],
  },
  {
    id: 'cat-prerolls',
    name: 'Pre-Rolls',
    order: 1,
    products: [
      {
        id: 'prod-preroll-sativa',
        name: 'Daytime Sativa Pre-Roll',
        price: 12,
        thc: '20%',
        cbd: '<1%',
        weight: '1g',
        brand: 'Saints Joints',
        strain: 'sativa',
        inStock: true,
        description: 'Energizing single-strain pre-roll for daytime creativity.',
      },
      {
        id: 'prod-preroll-indica',
        name: 'Nighttime Indica Pre-Roll',
        price: 12,
        thc: '22%',
        cbd: '<1%',
        weight: '1g',
        brand: 'Saints Joints',
        strain: 'indica',
        inStock: true,
        description: 'Relaxing indica blend for evening wind-down.',
      },
      {
        id: 'prod-preroll-hybrid',
        name: 'Hybrid Pack (5-Pack)',
        price: 35,
        thc: '21%',
        cbd: '<1%',
        weight: '2.5g',
        brand: 'Lowell Herb Co.',
        strain: 'hybrid',
        inStock: true,
        description: 'Five perfectly rolled hybrid joints in a reusable tin.',
      },
    ],
  },
  {
    id: 'cat-edibles',
    name: 'Edibles',
    order: 2,
    products: [
      {
        id: 'prod-gummies',
        name: 'Mango Gummies',
        price: 18,
        thc: '100mg',
        cbd: '<1%',
        weight: '10pk',
        brand: 'Kiva Confections',
        inStock: true,
        description: 'Tropical mango gummies with 10mg THC per piece.',
      },
      {
        id: 'prod-chocolate',
        name: 'Dark Chocolate Bar',
        price: 24,
        thc: '100mg',
        cbd: '<1%',
        weight: '1 bar',
        brand: 'Kiva Confections',
        inStock: true,
        description: 'Rich 60% dark chocolate with 10mg scored doses.',
      },
      {
        id: 'prod-mints',
        name: 'Peppermint Mints',
        price: 16,
        thc: '40mg',
        cbd: '20mg',
        weight: '20pk',
        brand: 'Breez',
        inStock: true,
        description: 'Microdose mints with 2mg THC and 1mg CBD each.',
      },
    ],
  },
  {
    id: 'cat-concentrates',
    name: 'Concentrates',
    order: 3,
    products: [
      {
        id: 'prod-live-resin',
        name: 'Live Resin Badder',
        price: 55,
        thc: '78%',
        cbd: '<1%',
        weight: '1g',
        brand: 'Raw Garden',
        strain: 'hybrid',
        inStock: true,
        description: 'Flash-frozen flower extraction bursting with terpenes.',
      },
      {
        id: 'prod-shatter',
        name: 'Lemon Shatter',
        price: 40,
        thc: '82%',
        cbd: '<1%',
        weight: '1g',
        brand: 'Moxie',
        strain: 'sativa',
        inStock: true,
        description: 'Citrus-forward shatter with glass-like consistency.',
      },
      {
        id: 'prod-rosin',
        name: 'Solventless Rosin',
        price: 65,
        thc: '75%',
        cbd: '<1%',
        weight: '1g',
        brand: 'Blue River',
        strain: 'indica',
        inStock: true,
        description: 'Premium heat-and-pressure rosin, solventless and pure.',
      },
    ],
  },
  {
    id: 'cat-vapes',
    name: 'Vapes',
    order: 4,
    products: [
      {
        id: 'prod-cart',
        name: 'Strawberry Cough Cartridge',
        price: 35,
        thc: '85%',
        cbd: '<1%',
        weight: '1g',
        brand: 'Stiiizy',
        strain: 'sativa',
        inStock: true,
        description: 'Sweet strawberry distillate cartridge with a smooth finish.',
      },
      {
        id: 'prod-disposable',
        name: 'Live Resin Disposable',
        price: 42,
        thc: '80%',
        cbd: '<1%',
        weight: '0.5g',
        brand: 'PlugPlay',
        strain: 'hybrid',
        inStock: true,
        description: 'All-in-one rechargeable disposable with live resin terpenes.',
      },
      {
        id: 'prod-battery',
        name: '510 Thread Battery',
        price: 15,
        weight: '1 unit',
        brand: 'PAX',
        inStock: true,
        description: 'Rechargeable 510 battery with three temperature settings.',
      },
    ],
  },
  {
    id: 'cat-topicals',
    name: 'Topicals',
    order: 5,
    products: [
      {
        id: 'prod-balm',
        name: 'Cooling Relief Balm',
        price: 30,
        thc: '50mg',
        cbd: '200mg',
        weight: '2oz',
        brand: 'Lord Jones',
        inStock: true,
        description: 'Menthol-infused CBD balm for targeted soothing relief.',
      },
      {
        id: 'prod-lotion',
        name: 'Hydrating Body Lotion',
        price: 28,
        thc: '25mg',
        cbd: '150mg',
        weight: '4oz',
        brand: 'Cannuka',
        inStock: true,
        description: 'Creamy daily lotion with CBD and manuka honey.',
      },
    ],
  },
];

export function createStarterConfig(): Partial<MenuConfig> & { categories: Category[] } {
  return {
    dispensaryName: STARTER_DISPENSARY_NAME,
    categories: JSON.parse(JSON.stringify(starterCategories)) as Category[],
  };
}
